name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_native:
    name: Native Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --verbose
      - run: cargo test --verbose
  build_wasm:
    name: WASM Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          # WASI builds don't currently work because zstd doesn't correctly build
          # I put up a PR to fix it https://github.com/gyscos/zstd-rs/pull/183. Once a new version of zstd
          # is released, we can update the dependency in `async_compression`, and then enable this build
          # - wasm32-wasi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v3
      - run: rustup target add ${{ matrix.target }}
      - run: cargo build --verbose --target ${{ matrix.target }}
